platform :ios, "9.3"
use_frameworks!

target 'MailcheckSwift_Example' do
  pod 'MailcheckSwift', :path => '../'

  target 'MailcheckSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.0'
    pod 'Nimble', '~> 7.3.0'
  end
end
